### ISSUE TITLE
The database is falling behind

### ISSUE THREAD

**Issue by MattStammers** [seungjaeryanlee/rldb#81]
Thanks for making this. It was a really useful easy to access initial resource on deep learning. However, your database is now pretty old and starting to fall behind. I cannot reconcile your data with all the up-to-date benchmarks: https://paperswithcode.com/task/atari-games.

**Comment by seungjaeryanlee** [comment]
Thanks! I'd recommend you take a look at the paperswithcode leaderboard for now - I am planning to rebuild the DB but it'll probably take some time.
